 /*
 * This source file was generated by the Gradle 'init' task
 */
package org.tbs;
import org.tbs.entities.User;
import org.tbs.services.UserBookingService;

import java.util.*;

public class App {

    private static final Scanner scanner = new Scanner(System.in);
    private static final UserBookingService userBookingService = new UserBookingService();

    public static void main(String[] args) {
        appConsole();
    }

    private static void appConsole() {
        User loggedInUser;
        while (true) {
            System.out.println("""
                    Welcome to TBS
                    The following operations are supported:
                    0. exit
                    1. login
                    2. signup
                    Which operation do you want to perform ? (press the index of the operation)
                    """);
            Integer operation = scanner.nextInt();
            System.out.println(operation);
            if(operation == 0) {
                return;
            } else if(operation == 1) {
                loggedInUser = login();
                if(loggedInUser == null) {
                    System.out.println("Invalid username or password!");
                }
            } else if(operation == 2) {
                loggedInUser = signup();
                if(loggedInUser == null) {
                    System.out.println("User with username {} already exists!");
                }
            } else {
                System.out.println("Invalid operation!");
            }
        }
    }

    private static User signup() {
        System.out.println("Enter your username:\n");
        String name = scanner.nextLine();
        System.out.println("Enter your password: (no spaces are allowed\n)");
        String password = scanner.next();
        return userBookingService.signup(name, password);
    }

    private static User login() {
        System.out.println("Enter your username:\n");
        String name = scanner.nextLine();
        System.out.println("Enter your password: (no spaces are allowed\n)");
        String password = scanner.next();
        return userBookingService.login(name, password);
    }
}
